services:
  minio:
    image: minio/minio:latest
    container_name: anfa-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: anfa-admin
      MINIO_ROOT_PASSWORD: anfa-password-2026
    volumes:
      - anfa-minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  anfa-minio-data:
    external: true